<?php
/**
 * Generated configuration file
 * Generated by: phpMyAdmin 5.2.0-rc1 setup script
 * Date: Mon, 18 Apr 2022 21:13:15 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: 127.0.0.1 [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = '';
$cfg['Servers'][$i]['host'] = '127.0.0.1';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = 'aRhpT(PRy6kf';



/* End of servers configuration */

$cfg['blowfish_secret'] = 'r:>|SrS-rJR[,E^?Mwv{cTzW^M|zu7cN';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
